- name: Prepare for execution on a dynamic host
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Fail if target_host variable is not provided
      ansible.builtin.fail:
        msg: "The 'target_host' variable was not defined. This playbook requires it to be passed as an extra variable."
      when: target_host is not defined

    - name: Add the API-specified host to our inventory
      ansible.builtin.add_host:
        name: "{{ target_host }}"
        groups: remote_targets
        ansible_host: "{{ target_host }}"
        ansible_connection: ssh
      changed_when: false
      when: target_host is defined

- name: Perform tasks on the dynamic target host
  hosts: remote_targets
  gather_facts: true
  tasks:
    - name: Debug connection variables
      debug:
        msg:
          - "ansible_user={{ ansible_user | default('not set') }}"
          - "ansible_connection={{ ansible_connection | default('not set') }}"
          - "ansible_host={{ ansible_host | default('not set') }}"
    - name: Ping the host to verify connectivity
      ansible.builtin.ping:

    - name: Print the Fully Qualified Domain Name (FQDN) of the target
      ansible.builtin.debug:
        msg: "Successfully connected to {{ ansible_fqdn }}."

    - name: Print all gathered facts
      debug:
        var: ansible_facts

    - name: Check the hostname
      ansible.builtin.command:
        cmd: hostname
      register: hostname_result

    - name: Display the hostname
      ansible.builtin.debug:
        var: hostname_result.stdout
